name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      # 1) Check out code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Install dependencies (Ubuntu + GCC/G++)
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++
          # If you want to ensure CMake uses gcc/g++ explicitly:
          export CC=gcc
          export CXX=g++

      # 3) Configure (CMake)
      - name: Configure (CMake)
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # 4) Build
      - name: Build
        shell: bash
        run: |
          cmake --build build --config ${{ matrix.build_type }}

      # 5) Run tests
      - name: Test
        shell: bash
        run: |
          ctest --test-dir build --output-on-failure
